### ISSUE TITLE
Please kindly provide a sample .env.local file

### ISSUE THREAD

**Issue by henrywithu** [jorge-menjivar/unSAGED#32]
Thanks you for your project

**Comment by Kisaragi-ng** [comment]
this my env which i use so far:

```
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=
SUPABASE_JWT_SECRET=
NEXTAUTH_SECRET=
NEXT_PUBLIC_DEBUG_MODE=true
NEXTAUTH_URL=http://mylocal.domain:3000
```

I tried to deploy it using docker-compose.yml, although I still get warning for non-persistent storage.

```yml
version: "3"
services:
  unsaged:
    container_name: unsaged
    build: .
    env_file:
      - .env.local
    ports:
      - 3000:3000
    volumes:
      - ./data:/app/data
    restart: always
```

I noticed that everytime I changed `.env.local`, I have to rebuild the image all over again. not using the principle like usual docker images where I can change my env, and then i can just restart the container.
